name: Create Unity Package

on: push

env:
  ASSET_DIR: Assets/OatsUtil
  ASSET_NAME: OatsUtil  

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Make metalist
      run: |
        echo "$ASSET_DIR.meta" > metaList
        find ./$ASSET_DIR/ -name \*.meta >> metaList

    - run: mkdir packageBuild

    - name: Build asset package
      uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'packageBuild/${{ $ASSET_NAME }}.unitypackage'
        include-files: metaList

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        path: packageBuild
        name: ${{ $ASSET_NAME }}_package
